namespace Libgit2
{
    public enum GitErrorCode : int
    {
        /// <summary>
        /// No error
        /// </summary>
        Ok = 0,
        /// <summary>
        /// Generic error
        /// </summary>
        Error = -1,
        /// <summary>
        /// Requested object could not be found
        /// </summary>
        NotFound = -3,
        /// <summary>
        /// Object exists preventing operation
        /// </summary>
        Exists = -4,
        /// <summary>
        /// More than one object matches
        /// </summary>
        Ambiguous = -5,
        /// <summary>
        /// Output buffer too short to hold data
        /// </summary>
        BufferToSmall = -6,
        /// <summary>
        /// <para>
        /// <see cref="UserDefined"/> is a special error that is never generated by libgit2.  
        /// </para>
        /// <para>
        /// You can return it from a callback (e.g to stop an iteration) to know that it was 
        /// generated by the callback and not by libgit2.
        /// </para>
        /// </summary>
        UserDefined = -7,
        /// <summary>
        /// Operation not allowed on bare repository
        /// </summary>
        BareRepo = -8,
        /// <summary>
        /// HEAD refers to branch with no commits
        /// </summary>
        UnbornBranch = -9,
        /// <summary>
        /// Merge in progress prevented operation
        /// </summary>
        Unmerged = -10,
        /// <summary>
        /// Reference was not fast-forwardable
        /// </summary>
        NonFastForward = -11,
        /// <summary>
        /// Namespecor refspec was not in a valid format
        /// </summary>
        InvalidSpec = -12,
        /// <summary>
        /// Checkout conflicts prevented operation
        /// </summary>
        Conflict = -13,
        /// <summary>
        /// Lock file prevented operation
        /// </summary>    
        Locked = -14,
        /// <summary>
        /// Reference value does not match expected
        /// </summary>
        Modified = -15,
        /// <summary>
        /// Authentication error
        /// </summary>
        AuthenticationFailure = -16,
        /// <summary>
        /// Server certificate is invalid
        /// </summary>
        InvalidCertificate = -17,
        /// <summary>
        /// Patch/merge has already been applied
        /// </summary>
        AlreadyApplied = -18,
        /// <summary>
        /// The requested peel operation is not possible
        /// </summary>
        PeelImpossible = -19,
        /// <summary>
        /// Unexpected EOF
        /// </summary>
        EndOfFile = -20,
        /// <summary>
        /// Invalid operation or input
        /// </summary>
        Invalid = -21,
        /// <summary>
        /// Uncommitted changes in index prevented operation
        /// </summary>
        Uncommited = -22,
        /// <summary>
        /// The operation is not valid for a directory
        /// </summary>
        Directory = -23,
        /// <summary>
        /// Internal only
        /// </summary>
        Passthrough = -30,
        /// <summary>
        /// Signals end of iteration with iterator
        /// </summary>
        EndofIterator = -31,
    }
}
